Features temp
Mar12358/book-an-appointment pull request #29
Opened 2023-09-30 02:49 UTC by edahigure

5. When the user clicks the "Add item" link in the navigation panel they can see a form for adding a new item.

6. Make the app responsive, creating both mobile and desktop versions.

##### Additional features - Required for teams with 3-4 & 5 members (optional for others)

7. When the user clicks the "Delete item" link in the navigation panel they can see a list of all items with title and "Delete" button.
   - When the user clicks the "Delete" button, the selected item is marked as removed and does not show on the main list anymore.

2023-09-30 13:44 UTC, Cabraham1 requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @edahigure  :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers, and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 13:44 UTC, Cabraham1 commented on app/javascript/components/DeleteLecture.js
> +
- [ ] Nice work so far on your project but i will kindly  suggest you add a useEffect to rel-render the components when a lecture is deleted

2023-09-30 15:14 UTC, Mar12358 requested changes
## You did an amazing job @edahigure ! 👏 
### ♻️  Changes Required ♻️ 
- I kindly suggest to change "Greetings" into an appropriate name, since that name is falling from a different project.
You can check on my commentes below, where I pointed out all the places where there is a Greetings. Sorry for the repetitive comments.

2023-09-30 15:14 UTC, Mar12358 commented on app/javascript/pages/Greetings.js
> +import './Greetings.css';
I kindly suggest to use an appropriate name for this css file.

2023-09-30 15:14 UTC, Mar12358 commented on app/javascript/pages/Greetings.css
I kindly suggest to use an appropriate name for this.

2023-09-30 15:14 UTC, Mar12358 commented on app/javascript/pages/Greetings.js
I kindly suggest to use an appropriate name for this.

2023-09-30 15:14 UTC, Mar12358 commented on app/javascript/pages/Greetings.js
> +export default function Greetings() {
I kindly suggest to use an appropriate name for this.

2023-09-30 15:14 UTC, Mar12358 commented on app/javascript/application.js
> +import Greetings from './pages/Greetings';
I kindly suggest to use an appropriate name for this.

2023-09-30 15:14 UTC, Mar12358 commented on app/javascript/application.js
> +        <Route path="delete_lecture" element={<Greetings />} />
I kindly suggest to use an appropriate name for this.

2023-10-01 15:37 UTC, Mar12358 requested changes
### Hi @edahigure !
Great job implementing changes. 👏 
## Changes Required ♻️ 
**This is important for devise to work propperly**:
- Please see the comment below.

2023-10-01 15:37 UTC, Mar12358 commented on app/controllers/application_controller.rb
> +  #  before_action :authenticate_user! # Uncomment this line to require authentication for all pages
Commenting this line will allow you to navigate to the page with no authentication, it also lets you do the API requests with no authentication, and the current user will forever be what is in local storage, if you have it already, if not, meaning it is the first time you navigate to the page, it will fail when creating a reserve, due to no current user existence.
- Have you tried to log out? You will have to specifically navigate /users/sign_up to sign up. But we want to automatically take you there if not logged in, and don't allow you to navigate through the page if so.
- Why did you commented this line? I see the application is working fine Uncommenting this line.
- [ ] **Please, uncomment this line.**

2023-10-03 16:43 UTC, Mar12358 approved these changes
Great! Now Devise will work approprietly.
Thanks for considering the changes.
Approved!! 💯 
Time to merge! 🎉

2023-10-03 16:44 UTC, merged