Book an Appointment features
Mar12358/book-an-appointment pull request #37
Opened 2023-10-04 15:57 UTC by Mar12358

Team members: @Mar12358, @edahigure and @Cabraham1 
## Added Features:
### General requirements

- [No linter errors](https://github.com/microverseinc/linters-config).
- Correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Documented in a [professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

### HTML/CSS, JavaScript, and Ruby requirements

- Following  [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- Following [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).
- Following[best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

### Project requirements

#### Basics

- Following the layout of [the provided design](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign). Changing the titles, descriptions, and photos - in order to create a website about Lectures (Classes).

#### Features
1. Full documentation for the API.
  ![image](https://github.com/Mar12358/book-an-appointment/assets/120040536/6489f4e7-108e-49b4-96c9-2b04dbe1a160)

2. The user logs in to the website, only by typing the username and password.
![image](https://github.com/Mar12358/book-an-appointment/assets/120040536/0c2b9807-0240-450a-bb3e-5ce97a2b5efe)
![image](https://github.com/Mar12358/book-an-appointment/assets/120040536/5a45265e-4fe7-47c6-9e03-d10907a8e60c)

3. In the navigation panel, the user can see links to:
   - Lectures.
   - "Reserve" form.
   - "My reservations".
   - "Add Lecture" (the link is visible to everybody).
   - "Delete Lecture" (the link is visible to everybody).
4. On the main page, the user can see a list of Lectures.
![image](https://github.com/Mar12358/book-an-appointment/assets/120040536/e8ccf8eb-b739-44d7-8beb-4cc0c2574567)

5. When the user selects a specific Lecture, they can see the details page.

   - In the details page, the user can click the "Reserve" button.

6. When the user clicks the "Add Lecture" link in the navigation panel they can see a form for adding a new item.
![image](https://github.com/Mar12358/book-an-appointment/assets/120040536/27fd393d-2063-4794-90d9-c8b9da88a1d4)

7. Make the app responsive, creating both mobile and desktop versions.

8. When the user clicks the "Delete Lecture" link in the navigation panel they can see a list of all items with title and "Delete" button.
   - When the user clicks the "Delete" button, the selected lecture is marked as removed and does not show on the main list anymore.

- To reserve an appointment, the user has to select a date and city (username and selected item are autofilled).
  - The user can also access the "Reserve" page from the navigation panel. In that case only username is autofilled.
![image](https://github.com/Mar12358/book-an-appointment/assets/120040536/d7c8e48f-8d01-4d89-8ad1-b55d0b8fb9bd)

9. When the user clicks the "My reservations" link in the navigation panel they can see a list of their reservations (with information about item name, date and city).
![image](https://github.com/Mar12358/book-an-appointment/assets/120040536/052ab2c8-9799-4b67-87c6-b6768d64860f)

##### Additional features

10. In the Reservation List, there is a buttn for deleting a each reservation. When the user clicks the "Delete" button, the selected reservation is marked as removed and does not show on the main list anymore.

11. Propper user authentification using Username and password

#### Technical set up

- Repository on GitHub and use Gitflow.
- Useage of Postgres as the database
- Used Rails to create backend API.
- Use React & Redux to create frontend UI.
- The team chose to do the project as one App .
- We give appropriate credit to the author on the README file. [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/).

2023-10-04 17:42 UTC, Meltrust requested changes
Hi @Mar12358 ,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Nice code organization ✔️ 
-  App is working well on Firefox✔️ 
-  Good readme ✔️ 




#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-10-04 17:42 UTC, Meltrust commented on README.md
> +- Set your postgres username and password, do so on `config/database.yml`. To get instructions on this, open `config/database_sample.yml`.
-  [ ] Your project does not include any of these 2 files mentioned here config/database.yml and/or config/database_sample.yml.

Kindly, include said file or the instructions about how to create one correctly a functioning `database.yml` for your project so your users can easily create the database.  👍

_In order to be able continue the review, I'll create a generic one for my local dev._

2023-10-04 17:42 UTC, Meltrust commented on README.md
> +### Setup <a name="setup"></a>
- [ ] Kindly, include in your instructions the required db commands that your users will need to run your backend app: ``rails db:create, rails db:migrate, rails db:seed``. 👍

2023-10-04 17:42 UTC, Meltrust commented on app/controllers/api/v1/lectures_controller.rb
> +  end
- [ ] What happens if the lecture is not successfully destroyed?  Kindly, add some error handling. 👍

2023-10-04 17:42 UTC, Meltrust commented on app/javascript/application.js
> +function App() {
- [ ]  Please, kindly refactor this and all other functions in your project to ES6 arrow functions, so your code complies with the latest standards.

Refactoring is easy:

```javascript
const App = () => {
  // ...
}
```

## Explanation

The `function` keyword has been soft deprecated in almost all the software industry in favor of ES6 arrow functions. This means, almost nobody uses it anymore, so much that it's considered a non-best practice.

You can do a search in Vscode for the "function" word, and correct as needed.  Shouldn't take you more than 5-10 min so don't worry:

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/d1bb644e-f0aa-4b68-9793-09e0fcd70b88)


That way, your code will meet the latest standards. 💪

2023-10-04 17:42 UTC, Meltrust commented on app/javascript/application.js
> +function App() {
- [ ] The mobile styling implementation is questionable:

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/2c3f91ab-14e2-4f97-9c48-2e3cd6581c06)


![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/72524be8-2cda-466b-9216-72f19b7c595f)

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/96e4a830-49ed-4c94-a829-3436fc5a21e8)

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/1d6399f3-e070-4e3b-8391-0aafd8b5ff74)

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/1fb13e43-805d-4492-ba41-b3e08d53f925)

This is in most cases because the navbar overflows with the content.  On the login page, the form does not fit the screen.

Kindly touch up your styling a little so the navbar is consistent with the content.  Also ensure the content fits the screen 👍

2023-10-04 17:42 UTC, Meltrust commented on app/javascript/application.js
> +function App() {
- [ ] Your app's auth is working well on Firefox:

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/b911063a-9531-4884-8a58-e828b7bdb368)

However, I couldn't make it work in Chrome or Edge:

Local storage:

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/be5416db-fc41-4343-97ed-1a04ba70e58c)

Browser network tab:

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/8f6f3edd-6bc1-4318-9105-71a4a5000c3f)

Browser console:

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/c2cd0924-56f4-46ae-b3da-477795e66bc4)

Rails console:

![image](https://github.com/Mar12358/book-an-appointment/assets/57421823/7529e383-a27b-4e8a-99b0-79b89466d8c3)


This seems to be because the browser's local storage on Chrome and Edge is not being correctly populated with the `current_user`  value, so the server rejects it and throws an unauthorized error.  

I happen to be a Firefox user myself and that is my main browser.  However, chances are the final evaluator and/or potential employers and/or most reviewers will just use Chrome to test your project.  I strongly suggest you make your project compatible with Chrome, this will save you lots of trouble.

_If this works on your end and you are indeed using Chrome, that means your project requires special instructions/procedures in order to be run correctly.  In that case, kindly include those instructions on your readme._

Since the auth worked for me on Firefox, this is optional, but really strongly suggested due to the above reasons.  👍

2023-10-04 18:00 UTC, Mar12358 commented on README.md
> +- Set your postgres username and password, do so on `config/database.yml`. To get instructions on this, open `config/database_sample.yml`.
Thanks. Done!

2023-10-04 18:02 UTC, Mar12358 commented on app/controllers/api/v1/lectures_controller.rb
> +  end
This method shouldn't be there, it is not used, It was added by mistake. In the rquirements it says that the item must be "marked" as removed. So we are not destroying it, we only give removed = true using a PATCH request. So, I delete this piece of code.

2023-10-04 18:08 UTC, Mar12358 commented on README.md
> +### Setup <a name="setup"></a>
When you build the project running `npm run project:build`, it also sets your db. That is specified in the documentation already

2023-10-04 18:27 UTC, Mar12358 commented on app/javascript/application.js
> +function App() {
@Meltrust 
I actually use Chrome, and it works perfectly. In your case, the `currentUuser` is not correctly saved into local storage because it wasn't allowed to fetch first. So the issue is that it's not being allowed to do API requests. We'll try to debug this. I see you marked it as OPTIONAL.

2023-10-05 20:41 UTC, Meltrust approved these changes
#### Hi @Mar12358,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- App is now working on Chrome and Edge✔️ 
- Functions are now ES6✔️ 
- database.yml is now included with instructions✔️
- Mobile styling has been vastly improved ✔️ 
- Commendable job ✔️  



Cheers and Happy coding!👏👏👏


------

2023-10-05 20:44 UTC, merged